### PR TITLE
Fixed resizing docs to refer the right path to spec in usage command

### PR DESCRIPTION
**Pull request by shihtiy-tw**
**Is this a bug fix or adding new feature?**

Document fix

**What is this PR about? / Why do we need it?**

The spec path was changed from "specs" to "spec"

**What testing is done?** 

yes

### CODE REVIEW

**Comment by wongma7** [comment]
/check-cla

/lgtm

what about renaming the directory to specs? the other examples are all named specs, seems the name is the true issue

**Comment by shihtiy-tw** [comment]
I have signed Contributor License Agreement (CLA).

**Comment by shihtiy-tw** [comment]
@wongma7  that's true... I will changed the directory to specs and update the README.

**Comment by shihtiy-tw** [comment]
I have rename the dir to "specs" as well.

**Pull request closed without merging**
