### PR TITLE
Fix supported filesystem types

### PR DESCRIPTION
**Pull request by AndrewSirenko**
#### What type of PR is this?

/kind cleanup

#### What is this PR about? / Why do we need it?

This PR fixes our list of supported filesystems by removing any instance of `ext2` from our project. EBS CSI Driver has not been able to manage volumes formatted with `ext2` for many versions. 

Our driver image has not supported the `ext2` binary since we've moved to a minimal base image, and resize doesn't work on `ext2` which presents a footgun for those attempting to edit the size of their PVC.

#### How was this change tested?

CI

#### Does this PR introduce a user-facing change?

```release-note
Remove ext2 from list of supported filesystem types.
```

### CODE REVIEW

**Review by torredil — COMMENTED** [review]
np: suggest explicitly mentioning that `ext2` is being removed from the list of supported fs types in the release notes.

ie, Fix list of supported filesystem types -> Remove `ext2` from list of supported filesystem types.

**Review by ElijahQuinones — APPROVED** [review]
LGTM double checked unit tests and confirmed we have no cases where we use ext2

**Pull request merged**
