### PR TITLE
Upgrade dependencies ahead of aws-ebs-csi-driver v1.26.0

### LINKED ISSUE #1849: Bump aws go sdk to > v1.47.11
**Is your feature request related to a problem?/Why is this needed**
Currently v1.47.8 of aws go sdk does not support new pod identities agent, bump to version >v1.47.11 

/feature

**Describe the solution you'd like in detail**
Bump version to at least v1.47.11
https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

**Describe alternatives you've considered**
Currently a more recent version is the only option

### PR DESCRIPTION
**Pull request by AndrewSirenko**
**Is this a bug fix or adding new feature?**
Dependency upgrades

**What is this PR about? / Why do we need it?**
Upgrade dependencies ahead of aws-ebs-csi-driver v1.26.0

~Note: This PR currently stacks on top of 1858, will rebase (and squash) once that is merged. Therefore, ignore the driver.go change.~

See commits for each change:
- Driver dependency upgrades
- CI job dependency upgrades
- Sidecar image upagrades
- Mock updates
- Fixing govet error after dependency upgrades: `tests/e2e/testsuites/testsuites.go:426:15: cannot use v1.ResourceRequirements{…} (value of type "k8s.io/api/core/v1".ResourceRequirements) as "k8s.io/api/core/v1".VolumeResourceRequirements value in struct literal`
- Add U7i attachment limits (Instance type currently in preview) 

Note: Closes #1849 

**What testing is done?** 
`make test` & `make verify`

### CODE REVIEW

**Comment by ConnorJC3** [comment]
/label tide/merge-method-squash

/lgtm

Will need to be rebased, so hold off on approving

**Comment by AndrewSirenko** [comment]
/hold

Due to needing to rebase post 1858

**Review by torredil — APPROVED** [review]
/retest
/lgtm

**Pull request merged**
