### PR TITLE
Add example IAM policy

### LINKED ISSUE #113: Provide IAM Policy Template for the driver
As a user, I would like to know what are the required the minimum IAM permission for the driver to function.

Ref #107

### PR DESCRIPTION
**Pull request by callahanca**
**Is this a bug fix or adding new feature?**
Fixes #113 
**What is this PR about? / Why do we need it?**
This adds an example IAM policy with the required permissions.
**What testing is done?** 
I ran the integration tests (`make test-integration`) on an EC2 instance using a role that had this policy attached.

### CODE REVIEW

**Comment by leakingtapan** [comment]
@callahanca thanks for the PR. 

Could you also update the [README](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/README.md#kubernetes-1)'s installation section by referring this example policy doc?

**Comment by callahanca** [comment]
@leakingtapan, sure - added the README reference.

**Pull request merged**
