### PR TITLE
Remove namespace field from manifests & template kubeletPath

### PR DESCRIPTION
**Pull request by Amos-85**
**Is this a bug fix or adding new feature?** 
Feature

**What is this PR about? / Why do we need it?**
Remove namespace kube-system from manifests & template kubelet path 

**What testing is done?** 
Installed the chart.

Issue #448

### CODE REVIEW

**Comment by Amos-85** [comment]
@wongma7 ,
is there any way to check the ebs controller logs ?
the volume creation is in pending state for some reason.
the e2e tests passed on my local k8s environment.
I just template the kubelet path with default values & removed the kube-system namespace from the manifests for being able to deploy it in any namespace when running `helm install -n <some-namespace>`

**Comment by wongma7** [comment]
@Amos-85 no, I should add that... To make the test print debugging info, you might need to edit  
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/tester/single-az-config.yaml#L92

That's where the test installs the driver using helm, do you see anything there that needs to be changed?

From the logs:

 NAME:   aws-ebs-csi-driver
LAST DEPLOYED: Sat Jul 11 10:33:10 2020
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/ClusterRole
NAME                           AGE
ebs-external-attacher-role     1s
ebs-external-provisioner-role  1s
ebs-external-resizer-role      1s
ebs-external-snapshotter-role  1s
ebs-snapshot-controller-role   1s
==> v1/ClusterRoleBinding
NAME                                 AGE
ebs-csi-attacher-binding             1s
ebs-csi-provisioner-binding          1s
ebs-csi-resizer-binding              1s
ebs-csi-snapshot-controller-binding  1s
ebs-csi-snapshotter-binding          1s
==> v1/DaemonSet
NAME          DESIRED  CURRENT  READY  UP-TO-DATE  AVAILABLE  NODE SELECTOR                                    AGE
ebs-csi-node  0        0        0      0           0          kubernetes.io/arch=amd64,kubernetes.io/os=linux  1s
==> v1/Deployment
NAME                READY  UP-TO-DATE  AVAILABLE  AGE
ebs-csi-controller  0/2    0           0          1s
==> v1/Pod(related)
NAME                       READY  STATUS             RESTARTS  AGE
ebs-snapshot-controller-0  0/1    ContainerCreating  0         1s
==> v1/Role
NAME                                    AGE
ebs-snapshot-controller-leaderelection  1s
==> v1/RoleBinding
NAME                                AGE
snapshot-controller-leaderelection  1s
==> v1/ServiceAccount
NAME                     SECRETS  AGE
ebs-csi-controller-sa    1        1s
ebs-snapshot-controller  1        1s
==> v1/StatefulSet
NAME                     READY  AGE
ebs-snapshot-controller  0/1    1s
==> v1beta1/CSIDriver
NAME             AGE
ebs.csi.aws.com  1s
NOTES:
To verify that aws-ebs-csi-driver has started, run:
    kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-ebs-csi-driver,app.kubernetes.io/instance=aws-ebs-csi-driver"

**Comment by Amos-85** [comment]
@wongma7 , 
Running the helm chart within debug mode won't help in this case cause
according to k8s events when e2e tests are running the pvc stuck on pending state and seems like the ebs controller can not create ebs volumes through amazon ec2 api.

if we'll expose ebs csi controller logs through the CI system it will help to debug any issues that relate to ebs controller.

**Comment by wongma7** [comment]
I think the reason the tests are failing is because they are using helm 2 and IIRC there is a difference between 2 and 3 wrt how namespace flag works.

/retest

**Pull request closed without merging**
