### PR TITLE
fix deploy stable ecr error kustomization file

### PR DESCRIPTION
**Pull request by ABNER-1**
**Is this a bug fix or adding new feature?**
This is a bug about ecr deploy error kustomization file

**What is this PR about? / Why do we need it?**
If do not fix this error, we can not deployed with this kustomization file.

**What testing is done?** 
I have tested in my eks cluster.

### CODE REVIEW

**Comment by ABNER-1** [comment]
tell a joke

**Comment by ayberk** [comment]
/lgtm
/approve

Thanks a lot!

**Pull request merged**
