### PR TITLE
Add ability to define kubeletPath and define namespace

### PR DESCRIPTION
**Pull request by Amos-85**
Signed-off-by: Amos Hadad <hadad22@netvision.net.il>

**Is this a bug fix or adding new feature?** new feature

**What is this PR about? / Why do we need it?** Add ability to define kubeletPath and define namespace

**What testing is done?**  helm install with defining a namespace and defining kubeletPath

Fixes: #448

### CODE REVIEW

**Comment by Amos-85** [comment]
I signed it

**Comment by Amos-85** [comment]
"I signed it"

**Comment by leakingtapan** [comment]
Please sign the CLA to get PR merged.

/ok-to-test

**Comment by Amos-85** [comment]
I signed it

**Comment by Amos-85** [comment]
"I signed it"

**Comment by Amos-85** [comment]
I signed it

**Comment by Amos-85** [comment]
Fixes: #448

**Comment by Amos-85** [comment]
@leakingtapan ,
According the test results it's looks like it doesn't create volumes.
Is there any way to view the pod logs that relate to the ebs driver?

**Pull request closed without merging**
