### PR TITLE
Fix default toleration

### PR DESCRIPTION
**Pull request by krmichel**
**Is this a bug fix or adding new feature?**
bug fix
**What is this PR about? / Why do we need it?**
This fixes issue #591

### CODE REVIEW

**Comment by krmichel** [comment]
/assign @leakingtapan
Can I get an ok to test for this?

**Comment by leakingtapan** [comment]
The taint was CriticalAddonOnly earlier but got removed due to some issue. Let me find it out

**Comment by krmichel** [comment]
> The taint was CriticalAddonOnly earlier but got removed due to some issue. Let me find it out

Okay sounds good.  That is kind of what I thought but I looked for a minute and couldn't find the commit where it got removed and thought maybe I just botched a merge.  Let me know what you find.  I can certainly remove it and make it so tolerations only show up if the user adds their own.

**Comment by leakingtapan** [comment]
here is the link: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/526#issuecomment-649998806

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/526 should be the right change, extra tolerations should be specified through `.Values.tolerations`. And if you care about turning of all toleration, please set `.Values.tolerateAllTaints` to false

**Comment by krmichel** [comment]
Closing in favor of #526

**Pull request closed without merging**
