### PR TITLE
Running multi-az e2e test using Nitro instance

### PR DESCRIPTION
**Pull request by leakingtapan**
**Is this a bug fix or adding new feature?**
Fixes: #237

### CODE REVIEW

**Comment by bertinatto** [comment]
LGTM. Could you elaborate what's the reasoning behind this change?

**Comment by leakingtapan** [comment]
@bertinatto this is for testing the nvme volume on Nitro instance. The idea is running the mult-az e2e test on the work nodes with c5 instance type. If the e2e test pass, it mean nvme is supported

**Comment by leakingtapan** [comment]
merge manually due to coverall [outage](https://status.coveralls.io/)

**Pull request merged**
