### PR TITLE
[DO NOT MERGE] PROW TEST DO NOT MERGE

### PR DESCRIPTION
**Pull request by ConnorJC3**
**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

**What testing is done?**

### CODE REVIEW

**Comment by ElijahQuinones** [comment]
retesting to see if Drew's dep bump fixed trivy /retest

**Comment by ConnorJC3** [comment]
/close

please do not retest this PR, use a different one, it does destructive things when the tests run

**Pull request closed without merging**
