### PR TITLE
EBS MultiAttach

### PR DESCRIPTION
**Pull request by sr-auto**
**Is this a bug fix or adding new feature?**
New Feature: EBS Multi Attach

**What is this PR about? / Why do we need it?**
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/449

**What testing is done?**

### CODE REVIEW

**Comment by sppwf** [comment]
Hi Guys,

Do you have updates over here?

Thanks
Sergiu Plotnicu

**Comment by jesseadev** [comment]
Hi all,

Any update on this?

Thank you!

**Comment by sr-caprx** [comment]
@AndyXiangLi @vdhanan Any chance you'll be reviewing this soon?

**Comment by sppwf** [comment]
Hi,

@AndyXiangLi do you think you can check the Pull Request and give your input over here? 
@sr-auto maybe you can check if there are other reviewers willing to take a look?

Thanks
Sergiu Plotnicu

**Comment by ksliu58** [comment]
Hi @sr-auto @sppwf ,

Multi-attach are only available for io2 and io1 volumes in some regions. Can you share some additional details on your use cases, and what you plan to resolve with Multi-attach?

Thanks.

**Pull request closed without merging**
