### PR TITLE
Add arm support

### PR DESCRIPTION
**Pull request by leakingtapan**
**Is this a bug fix or adding new feature?**
Fixes: #521

**What is this PR about? / Why do we need it?**
Add arm support

### CODE REVIEW

**Comment by leakingtapan** [comment]
/hold
blocked by: https://github.com/kubernetes-csi/external-provisioner/issues/381

**Comment by AWSNB** [comment]
> /hold
> blocked by: [kubernetes-csi/external-provisioner#381](https://github.com/kubernetes-csi/external-provisioner/issues/381)

@leakingtapan can we unblock as ^^ has been closed ?

would this get lgtm so it could get merged ?

**Comment by leakingtapan** [comment]
The blocking issue is there is no corresponding arm images for side car containers published on quay.io AFAIK. I can merge this PR if this work for u. @AWSNB

**Comment by AWSNB** [comment]
> The blocking issue is there is no corresponding arm images for side car containers published on quay.io AFAIK. I can merge this PR if this work for u. @AWSNB


i may be wrong, but the july 16 update covered that :  https://github.com/kubernetes-csi/external-attacher/commit/f5a420378dc8e19bda7bdb36c813d9b0223e031b

**Comment by msau42** [comment]
The upcoming releases for csi sidecars (~ end of the month) will also publish multi-arch images

**Comment by msau42** [comment]
The csi project has not tested any of the non-x86 images. They will be published on k8s.gcr.io/sig-storage only. quay.io/k8scsi is no longer going to get new images.

**Comment by leakingtapan** [comment]
Merging. Will create a separate issue to track how to enable side car arm images

**Pull request merged**
