### PR TITLE
Revert "Fix kustomize RBAC bindings to have namespace kube-system"

### LINKED ISSUE #946: Namespace changes in 1.1.0 breaks upgrades from 1.1.0 if not using default namespaces
/kind bug

**What happened?**
When upgrading to 1.1.0 from 1.0.0 all ClusterRoleBinding's and RoleBinding's were shifted in to the kube-system namespace while our deployment which references the [upstream overlays](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/deploy/kubernetes/overlays/stable?ref=f0011c9fc23afbcea3bd8af97627da8ad3dc1e84) is deployed to a namespace other than kube-system. This lead to relevant RBAC permissions being inaccessible to the ServiceAccount's that rely on them.

**What you expected to happen?**
Kustomize should be able to decide which namespace it deploys the aws-ebs-csi-driver to ensuring resources are not split between multiple namespaces.

**How to reproduce it (as minimally and precisely as possible)?**
1. Deploy aws-ebs-csi-driver to a non-default namespace using the base below.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable?ref=8b1e568654937ac42ff750fbee79b207d1e63016
namespace: foo
 
```
2. Upgrade to 1.1.0 by using the base below.
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable?ref=f0011c9fc23afbcea3bd8af97627da8ad3dc1e84
namespace: foo
 
```
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: v1.21.0
Server Version: v1.20.4-eks-6b7464
- Driver version:
1.0.0 upgrading to 1.1.0

### PR DESCRIPTION
**Pull request by TheRealDwright**
This reverts commit `3716e5ef3175bdbb6745018f9646957b5a635eac`

**Is this a bug fix or adding new feature?**
Fixes #946 946

**What is this PR about? / Why do we need it?**
Issue described in ticket

**What testing is done?**

### CODE REVIEW

**Comment by TheRealDwright** [comment]
"I signed it"

**Comment by krmichel** [comment]
After a little reading, since I have not used kustomize, it looks like they have special handling to adjust the namespace for role bindings and cluster role bindings if the manifest has default set as the namespace for the subjects field.  So, given I have no experience with this, it seems like this is the kustomzie way to handle bindings.

https://github.com/kubernetes-sigs/kustomize/blob/release-kustomize-v4.2/api/filters/namespace/namespace.go#L93-L106

**Comment by wongma7** [comment]
thanks, I was not aware kustomize already handled this for us as long as we leave it "default"

/lgtm
/ok-to-test
/approve

I'll cherry pick this int orelease 1.1 branch because that's where the README points.

**Comment by wongma7** [comment]
2021-06-22 19:00:44 [✖]  AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "Cluster test-cluster-5973-k8s-local failed to stabilize: Internal Failure" 

weird

/retest

**Pull request merged**
