### PR TITLE
Missing RBAC rule - allow to patch volumesnapshotcontent.

### PR DESCRIPTION
**Pull request by michalschott**
**Is this a bug fix or adding new feature?**

Bug fix for deployment manifests / helm chart.

**What is this PR about? / Why do we need it?**

Because ebs-csi-controller service account is unable to patch `volumesnapshotcontent` its getting bit spammy about it:
```
ebs-csi-controller-59c596cfb7-b5twg csi-snapshotter E0125 14:40:11.248298       1 snapshot_controller_base.go:265] could not sync content "snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439": failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439: "snapshot controller failed to update snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
ebs-csi-controller-59c596cfb7-b5twg csi-snapshotter I0125 14:40:11.248331       1 event.go:285] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439", UID:"dcc63ee1-6be4-430f-8ba3-0a3c02c53540", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"513176977", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439: "snapshot controller failed to update snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
ebs-csi-controller-59c596cfb7-b5twg csi-snapshotter I0125 14:40:43.249153       1 snapshot_controller.go:291] createSnapshotWrapper: Creating snapshot for content snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439 through the plugin ...
ebs-csi-controller-59c596cfb7-b5twg csi-snapshotter E0125 14:40:43.258531       1 snapshot_controller.go:107] createSnapshot for content [snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439]: error occurred in createSnapshotWrapper: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439: "snapshot controller failed to update snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
ebs-csi-controller-59c596cfb7-b5twg csi-snapshotter E0125 14:40:43.258557       1 snapshot_controller_base.go:265] could not sync content "snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439": failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439: "snapshot controller failed to update snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
ebs-csi-controller-59c596cfb7-b5twg csi-snapshotter I0125 14:40:43.258647       1 event.go:285] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439", UID:"dcc63ee1-6be4-430f-8ba3-0a3c02c53540", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"513176977", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439: "snapshot controller failed to update snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-796d3be6-0b1f-484b-9738-7f9c86493439\" is forbidden: User \"system:serviceaccount:kube-system:ebs-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"
```

**What testing is done?** 
Locally updated cluster role binding with missing permission.

### CODE REVIEW

**Comment by michalschott** [comment]
Looks like this is required for `csi-snapshotter` v5.0.0+

**Comment by Xyaren** [comment]
We are also having this issue. 
Please merge <3

**Comment by michalschott** [comment]
Solved in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1257

**Pull request closed without merging**
