### PR TITLE
Update to use 1.16 cluster with inline test enabled

### PR DESCRIPTION
**Pull request by leakingtapan**
**Is this a bug fix or adding new feature?**
Changes made:
* Upgrade cluster version to 1.16.1
* update helm to 2.16 to be compatible with 1.16 k8s cluster
* switch to use ginkgo parallel for migration test
* Update for golang 1.13

/cc @wongma7

### CODE REVIEW

**Comment by wongma7** [comment]
Dang:
Sep  5 18:16:16.705: INFO: At 2019-09-05 18:11:09 +0000 UTC - event for exec-volume-test-aws-2hwb: {attachdetach-controller } FailedAttachVolume: AttachVolume.NodeUsingCSIPlugin failed for volume "vol1" : inline volume migration not yet supported

**Comment by wongma7** [comment]
OK, confirmed the cluster needs to be 1.16: https://github.com/kubernetes/kubernetes/pull/80048

**Comment by leakingtapan** [comment]
inline volume e2e test are running. failures are due to:
```
Nov  6 20:35:20.155: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for exec-volume-test-aws-twkn: {default-scheduler } Scheduled: Successfully assigned volume-1528/exec-volume-test-aws-twkn to ip-172-20-55-156.us-west-2.compute.internal
Nov  6 20:35:20.155: INFO: At 2019-11-06 20:30:05 +0000 UTC - event for exec-volume-test-aws-twkn: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "vol1" : rpc error: code = Internal desc = Could not get volume with ID "aws://us-west-2a/vol-00b29f34238b35df1": InvalidParameterValue: Value (aws://us-west-2a/vol-00b29f34238b35df1) for parameter volumes is invalid. Expected: 'vol-...'.
	status code: 400, request id: 67ef4c50-9b7f-4adc-8b7b-53d80bf31c0c
Nov  6 20:35:20.155: INFO: At 2019-11-06 20:30:06 +0000 UTC - event for exec-volume-test-aws-twkn: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "vol1" : rpc error: code = Internal desc = Could not get volume with ID "aws://us-west-2a/vol-00b29f34238b35df1": InvalidParameterValue: Value (aws://us-west-2a/vol-00b29f34238b35df1) for parameter volumes is invalid. Expected: 'vol-...'.
	status code: 400, request id: cbcb0663-52e1-429a-8bed-110c0fc7e844
Nov  6 20:35:20.155: INFO: At 2019-11-06 20:30:07 +0000 UTC - event for exec-volume-test-aws-twkn: {attachdetach-controller } FailedAttachVolume: AttachVolume.Attach failed for volume "vol1" : rpc error: code = Internal desc = Could not get volume with ID "aws://us-west-2a/vol-00b29f34238b35df1": InvalidParameterValue: Value (aws://us-west-2a/vol-00b29f34238b35df1) for parameter volumes is invalid. Expected: 'vol-...'.
```
Fixed by: https://github.com/kubernetes/kubernetes/pull/84844

**Comment by leakingtapan** [comment]
golang is bumped to 1.13.4 recently: https://github.com/kubernetes/test-infra/commit/c9417055d5d6b99a62290168e6251a70308625e3

```
docker run -ti --rm --entrypoint go gcr.io/k8s-testimages/kubekins-e2e:v20191106-09649c7-master version
go version go1.13.4 linux/amd64
```

**Pull request merged**
