### PR TITLE
Example policy to support encrypted drives

### PR DESCRIPTION
**Pull request by challapradyumna**
**Is this a bug fix or adding new feature?**
Doc update

**What is this PR about? / Why do we need it?**
The example policy should include some sensible defaults for encrypted drives to work.

**What testing is done?** 
Used the policy to create drives

### CODE REVIEW

**Comment by torredil** [comment]
Thanks for raising this up. There's been a few issues related to IAM policies recently which indicates we should improve the documentation in this area. There are no benefits to giving the driver permissions it doesn't need, so a better long-term solution would be having a baseline IAM policy which contains the minimum permissions the driver requires to properly function, and then separately document additional permissions that can be added for other functionality such as snapshots and encrypted drives. The idea is that driver users shouldn't have to guess which policies they need to get something to work or provide more access than needed.

**Comment by challapradyumna** [comment]
Instead of updating the sample policy. I've added a note to the install doc itself with the necessary details.

**Review by torredil — APPROVED** [review]

**Pull request merged**
