### PR TITLE
chore: add requirements.in files with fixed versions to use in pip

### PR DESCRIPTION
**Pull request by echyam**
/kind cleanup

**Is this a bug fix or adding new feature?**
Makes pip install install fixed versions with a `xxx-requirements.in` file per package (aws, yamale, yamllint)

**What is this PR about? / Why do we need it?**
Verifies pip packages being installed with hashes.

**What testing is done?** 
Tested installing the affected packages via the modified script and able to successfully use them.
Successfully ran `make verify`, `make test`. `make test-integration` not available.

### CODE REVIEW

**Comment by AndrewSirenko** [comment]
@echyam I believe you need to sign the CLA

See this comment: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2012#issuecomment-2064905525

**Comment by ConnorJC3** [comment]
/ok-to-test

Thanks for signing the CLA, will try to get this reviewed next week

**Comment by echyam** [comment]
@ConnorJC3 any chance of update this week?

**Comment by ConnorJC3** [comment]
Sorry, got busy last week

/lgtm

**Review by AndrewSirenko — APPROVED** [review]
Thanks for this best-practice.

**Pull request merged**
