### PR TITLE
[chart] Update kubernetes-csi/livenessprobe

### LINKED ISSUE #1044: "Warning" LogLevel for LivenessProbe
**Is your feature request related to a problem?/Why is this needed**
I'd like to have an option to turn LivenessProbe to "Warning" mode. Currently, it generates a message every 10 seconds.  This creates a lot of entries in my logging system.

/feature

**Describe the solution you'd like in detail**
I'd like to have only warning, error messages in the log output.

**Describe alternatives you've considered**
I've tried set `logLevel: 1` but this doesn't change the number of messages.

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind feature

Fixes #1044

### CODE REVIEW

**Comment by ialidzhikov** [comment]
ping @wongma7 
for review/approval

**Comment by ialidzhikov** [comment]
ping @wongma7
for review/approval

**Comment by ialidzhikov** [comment]
ping @wongma7 @nckturner

**Comment by wongma7** [comment]
/lgtm
/approve

sorry for delay, I wanted to get v2.4.0 pushed to private ECR as well to keep the GCR and ECR kustomize in sync. Now the ECR public kustomize will drift out of sync anyway so ultimately I don't think it matters much if the templates go out of sync...as long as they are the same major version 

```
~ $ aws ecr get-login-password | docker login --username AWS --password-stdin 602401143452.dkr.ecr.us-west-2.amazonaws.com
    docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.4.0
```

**Comment by wongma7** [comment]
ref, table of sidecar image availability for ecr/ecr public: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1136#issuecomment-990374973

**Pull request merged**
