### PR TITLE
Enable volume modification through annotations

### PR DESCRIPTION
**Pull request by rdpsin**
The commit allows users to modify volume properties through PVC annotations. For more details, refer to the modify-volume doc.

**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

**What testing is done?**

### CODE REVIEW

**Review by ConnorJC3 — APPROVED** [review]
Long term, we should have unit/e2e tests for this, but otherwise lgtm

**Review by torredil — APPROVED** [review]

**Pull request merged**
