### PR TITLE
Change modifyVolumeRequestHandlerTimeout to a configurable option

### PR DESCRIPTION
**Pull request by andrewcharlton**
**Is this a bug fix or adding new feature?**
New feature

**What is this PR about? / Why do we need it?**
This PR changes the `modifyVolumeRequestHandlerTimeout`, which was previously hardcoded to 2 seconds, into an option that the user can specify. If it is not specified, this should be a complete no-op and default to 2 seconds as before.

The `modifyVolumeRequestHandlerTimeout` determines how long the controller will wait for additional volume modification calls before executing them and modifying the volume. When changing both the size and IOPs/Throughput of a volume simultaneously there are two calls made and they need to be coalesced together within this window for a single call to AWS to be made.  We have seen cases where the 2 seconds is not long enough for this to happen, and only a single one of those changes is made so we would like to extend the window for our use case, where it is more important that the change be atomic than it's latency.

Issue discussing this: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1911

**What testing is done?** 

Added unit test for the new option. Updated coalesce tests to ensure they use the value from the option.  

We have a fork with a larger timeout window running in our environment successfully.

### CODE REVIEW

**Comment by adolsalamanca** [comment]
Hello folks,
One important thing to note about this change:

it's very important to make sure that both `resizer` and `modifier` timeout args are higher than the specified `modify-volume-request-handler-timeout`, otherwise users might have contex timeout errors on requests from those to gRPC endpoints in csi-controller.

Timeouts both in `resizer` and `modifier` are by default 10s.

**Review by ConnorJC3 — APPROVED** [review]
/lgtm

**Comment by andrewcharlton** [comment]
> Maybe worth adding a comment about this to the code, or to the docs?

Thanks, I've added a comment in both the docs, and the descriptor for the flag.  I added an additional testcase that I'd missed for the flag as well.  Hope that's ok!

**Review by torredil — APPROVED** [review]
Thanks @andrewcharlton
/lgtm

**Review by ConnorJC3 — APPROVED** [review]
/lgtm
/label tide/merge-method-squash

**Review by AndrewSirenko — APPROVED** [review]
Thanks for this

**Pull request merged**
