### PR TITLE
Bump kOps k8s version to 1.27; Bump eksctl k8s version to 1.26

### PR DESCRIPTION
**Pull request by ConnorJC3**
**Is this a bug fix or adding new feature?**

"Feature"

**What is this PR about? / Why do we need it?**

Bumps the k8s versions we test against in CI

**What testing is done?** 

CI

### CODE REVIEW

**Comment by ConnorJC3** [comment]
/retest

1.27 images available: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-image-promo/1645852505256497152

**Comment by ConnorJC3** [comment]
/retest

https://groups.google.com/a/kubernetes.io/g/dev/c/hMjpAizpE7g

**Comment by torredil** [comment]
Cluster creation fails due to the `CSIMigrationAWS` feature gate:
```
Apr 20 17:58:16 i-05002d43aeb1aac3c kubelet[3362]: E0420 17:58:16.569690    3362 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: unrecognized feature gate: CSIMigrationAWS"
```

Changes to remove this feature gate in K8s 1.27+ have been merged but not yet released: https://github.com/kubernetes/kops/pull/15197.

**Review by torredil — APPROVED** [review]

**Pull request merged**
