### PR TITLE
Switch to use 1.17.0 for e2e test

### PR DESCRIPTION
**Pull request by leakingtapan**
**Is this a bug fix or adding new feature?**
Switch to use 1.17.0 for e2e test

### CODE REVIEW

**Comment by leakingtapan** [comment]
something wrong with inline volume

**Comment by wongma7** [comment]
I can pick this and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/410 up in a new PR soon if u need help, since 1.16 being deprecated

**Comment by leakingtapan** [comment]
Sounds good and go ahead @wongma7

**Comment by wongma7** [comment]
/close

now using 1.18 and i am gonna set the Complete feature gates in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/593

**Pull request closed without merging**
