### PR TITLE
Removing prestop hook for node-driver-registrar

### PR DESCRIPTION
**Pull request by tsunny**
**Is this a bug fix or adding new feature?**
Bug

**What is this PR about? / Why do we need it?**
See issue: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/747

**What testing is done?** 
Valid template

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
/approve
/ok-to-test
ty

**Comment by AndyXiangLi** [comment]
Test is failing because go.sum not up-to-date, #777 should fix the test issue

**Pull request merged**
