### PR TITLE
Add podAnnotations to snapshotController StatefulSet

### PR DESCRIPTION
**Pull request by snstanton**
**Is this a bug fix or adding new feature?**

New feature

**What is this PR about? / Why do we need it?**

This PR adds support for setting pod annotations on the snapshot controller.  This is useful for fluent-bit logging annotations.

### CODE REVIEW

**Comment by snstanton** [comment]
CLA signed

**Comment by wongma7** [comment]
/ok-to-test
/lgtm
/approve

I thought our chart was being inconsistent naming it podAnnotations instead of just annotations like in some other places but I see now podAnnotations refers to the statefulset's pod instead of statefulset itself...

You need to rebase just because the version got bumped

**Comment by snstanton** [comment]
Looks like the lgtm label got removed by the rebase for the version number change.  There were no code other code changes.

**Comment by snstanton** [comment]
I'm not sure how to proceed.  The PR was approved pending a rebase.  I rebased, then the PR wasn't re-approved before it needs to be rebased again.

**Comment by wongma7** [comment]
/lgtm

sorry about that

**Pull request merged**
