### PR TITLE
Release aws-ebs-csi-driver v1.34.0

### PR DESCRIPTION
**Pull request by AndrewSirenko**
**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

Releases aws-ebs-csi-driver v1.34.0

Please confirm Makefile, README.md, install.md, kustomize overlays, charts/aws-ebs-csi-driver/Chart.yaml all updated correctly

**What testing is done?** 

CI

### CODE REVIEW

**Review by ConnorJC3 — APPROVED** [review]
/lgtm
/retest

**Review by torredil — APPROVED** [review]
/lgtm
/approve

**Comment by AndrewSirenko** [comment]
Failing due to image not being available in ecr public.

**Pull request merged**
