### PR TITLE
Fix markdown issue in README.md

### PR DESCRIPTION
**Pull request by ialidzhikov**
**Is this a bug fix or adding new feature?**
/kind documentation

**What is this PR about? / Why do we need it?**
Fix markdown issue in README.md.

### CODE REVIEW

**Comment by wongma7** [comment]
/ok-to-test
/lgtm
/approve
thanks

**Comment by ialidzhikov** [comment]
@wongma7, any idea why `pull-aws-ebs-csi-driver-e2e-single-az` keeps failing? Issues with the cloudprovider account or with the tests/driver itself?

**Comment by ayberk** [comment]
Tests are failing for `io2`, which we have recently started supporting. io2 volumes seem to take longer to become available than our wait time right now. Since we have intermittent successful runs, we can increase the timeout as a short term workaround.

**Pull request merged**
