### PR TITLE
add ecr-private kustomize overlay

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
**Is this a bug fix or adding new feature?**
New feature.

**What is this PR about? / Why do we need it?**
Address @wongma7's comment on PR #1098: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1098#discussion_r733131616.

This will allow ECR Private to be used when pulling images. Advantages of this method include being able to use the ECR Endpoint and to target a specific AWS Region where the image will be pulled from.

I decided to use `ecr` as the overlay for ECR Private and `ecr-public` as the overlay for ECR Public for it to match the identifiers of both services used on their domains and when writing IAM policies for them.

**What testing is done?** 
Check that all images referenced on Kustomization are publicly available.

It's important to note that `602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/external-resizer` doesn't seem to be accessible to everyone. I opened a support ticket on AWS so this issue can be fixed (Case ID 9276886011).

### CODE REVIEW

**Comment by wongma7** [comment]
/ok-to-test

thanks

**Comment by wongma7** [comment]
Let me check out what's going on with external-resizer before merging

**Comment by wongma7** [comment]
Currently the latest available resizer image maintained by AWS is "v1.0.0" under the name "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer:v1.0.0". i.e. the repository "csi-resizer" as opposed to "external-resizer"

So let me get v1.1.0 (and also newer versions while at it?) pushed to "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer:v1.1.0" then we will have parity

/hold

**Comment by t0rr3sp3dr0** [comment]
I just updated the patch replacing `external-resizer` with `csi-resizer`. Also, I'll close the support ticket as you are already checking that.

**Comment by t0rr3sp3dr0** [comment]
Do you think we should move `./deploy/kubernetes/overlays/stable/kustomization.yaml` to `./deploy/kubernetes/overlays/stable/grc/kustomization.yaml`?

We could also make the ECR overlays use the GCR one as base so we don't need to update tags in multiple Kustomizations. But most of the tags for the ECR Public overlay would still need to be overwritten as images from the EKS-D registry have a suffix with the EKS version.

**Comment by wongma7** [comment]
I think a "default" `./deploy/kubernetes/overlays/stable/kustomization.yaml` is still needed in addition to 
`./deploy/kubernetes/overlays/stable/gcr/kustomization.yaml` but i am not sure how to achieve that cleanly. So I am fine if it is simply moved to `gcr` and the install instruction gets updated for next release.

and it makes sense to have ecr use gcr as base. The only potential issue there is if a (new) tag exists in gcr but not ecr since ecr is an imperfect mirror of gcr, but ideally if when bumping tags we always check they are actually pullable from all registries..

`./deploy/kubernetes/overlays/stable/kustomization.yaml` (== `./deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml` ? )
`./deploy/kubernetes/overlays/stable/ecr/kustomization.yaml`
`./deploy/kubernetes/overlays/stable/ecr-public/kustomization.yaml`
`./deploy/kubernetes/overlays/stable/gcr/kustomization.yaml`

I am still working on getting newer csi-resizer versions  into that 602401143452 account

**Comment by t0rr3sp3dr0** [comment]
I pushed another patch reorganizing the overlays in that way, with ecr-public being the default version for stable.

```sh
➜  aws-ebs-csi-driver git:(feat/ecr-private) kustomize build ./deploy/kubernetes/overlays/stable | grep 'image:'   
        image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.4.0
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v2.1.1-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-attacher:v3.1.0-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v3.0.3-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-resizer:v1.1.0-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.2.0-eks-1-18-3
        image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.4.0
        image: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.1.0-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.2.0-eks-1-18-3
```
```sh
➜  aws-ebs-csi-driver git:(feat/ecr-private) kustomize build ./deploy/kubernetes/overlays/stable/ecr-public | grep 'image:'
        image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.4.0
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v2.1.1-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-attacher:v3.1.0-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v3.0.3-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/external-resizer:v1.1.0-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.2.0-eks-1-18-3
        image: public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.4.0
        image: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.1.0-eks-1-18-3
        image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.2.0-eks-1-18-3
```
```sh
➜  aws-ebs-csi-driver git:(feat/ecr-private) kustomize build ./deploy/kubernetes/overlays/stable/ecr | grep 'image:' 
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v1.4.0
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner:v2.1.1
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-attacher:v3.1.0
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-snapshotter:v3.0.3
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer:v1.1.0
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.2.0
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-ebs-csi-driver:v1.4.0
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v2.1.0
        image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.2.0
```
```sh
➜  aws-ebs-csi-driver git:(feat/ecr-private) kustomize build ./deploy/kubernetes/overlays/stable/gcr | grep 'image:'
        image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.4.0
        image: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.1
        image: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
        image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
        image: k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
        image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
        image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v1.4.0
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
        image: k8s.gcr.io/sig-storage/livenessprobe:v2.2.0
```

**Comment by t0rr3sp3dr0** [comment]
I'll open a feature request on Kustomize for something that would allow us to add a suffix to image tags and check if that is something simple to implement.

If we have this feature, we can do something like

```yaml
images:
  - name: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner
    newName: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    tagSuffix: -eks-1-18-3
```

on the ecr-public overlay and manage versions only on the gcr overlay.

**Comment by t0rr3sp3dr0** [comment]
Feature request: https://github.com/kubernetes-sigs/kustomize/issues/4322

**Comment by wongma7** [comment]
/lgtm
thanks !

I won't be able to get v1.1.0 csi-resizer until monday next week though so will merge then

**Comment by wongma7** [comment]
csi resizer 1.1.0 is available in private ecr ( as are other sidecars, checked while I was at it).

/hold cancel

```
~ $ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer:v1.1.0
v1.1.0: Pulling from eks/csi-resizer
Digest: sha256:99e3f077dff5c07d14371a90b2b4cfd9081cc2100aeb080d8188684c4df9af24
Status: Downloaded newer image for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer:v1.1.0
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-resizer:v1.1.0

~ $ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner:v2.1.1
v2.1.1: Pulling from eks/csi-provisioner
Digest: sha256:104e62c8e2d5b89625074b4775542e5ee83215d9c369e3bc6a8f81a426328184
Status: Image is up to date for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner:v2.1.1
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-provisioner:v2.1.1
~ $ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-attacher:v3.1.0
v3.1.0: Pulling from eks/csi-attacher
e8614d09b7be: Already exists 
83849fdea226: Pull complete 
Digest: sha256:e12b5503a0ccf56752943a15ac4e410bdc28e8162991d160be848bdeffce059a
Status: Downloaded newer image for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-attacher:v3.1.0
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-attacher:v3.1.0
~ $ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.2.0
v2.2.0: Pulling from eks/livenessprobe
Digest: sha256:185bb9690c85e82ef22abc496b7af0e5d3d1e5ec4c1b8fdba7d8e01fee792f64
Status: Image is up to date for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.2.0
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/livenessprobe:v2.2.0
~ $ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-snapshotter:v3.0.3
v3.0.3: Pulling from eks/csi-snapshotter
e8614d09b7be: Already exists 
0b1c8d637f0f: Pull complete 
Digest: sha256:cae5244593aa223699cc62c4ee323c7667475847d0a43abb20ff3b90d19fe25d
Status: Downloaded newer image for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-snapshotter:v3.0.3
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-snapshotter:v3.0.3
~ $ docker pull 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v2.1.0
v2.1.0: Pulling from eks/csi-node-driver-registrar
Digest: sha256:f0d276d527ff628c1885ab507aa4f1c338047f75287a77267d5c6962b6a6121d
Status: Image is up to date for 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v2.1.0
602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/csi-node-driver-registrar:v2.1.0
```

**Pull request merged**
