### PR TITLE
Update index.yaml

### LINKED ISSUE #587: Helm repo index.yaml out of date
**Is your feature request related to a problem?/Why is this needed**
The current Helm repo index.yaml (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/gh-pages/index.yaml) is out of date and pointing to an older version.

/feature

**Describe the solution you'd like in detail**
Please update the Helm repo index.yaml and point it to the published release of the 0.7.0 Helm chart

**Describe alternatives you've considered**
Current work around is to source the helm chart directly from the release as in the provided directions

**Additional context**
This would make the Helm chart experience consistent and up to date

### PR DESCRIPTION
**Pull request by ayberk**
**What is this PR about? / Why do we need it?**
Updates the helm repo chart.

**What testing is done?** 
Published to my own repository and installed the new chart. Verified it installs `v0.7.1`.

Closes #587

### CODE REVIEW

**Comment by krmichel** [comment]
This only replaces the old version of the chart with a newer one in the chart repository.  It should contain all the available versions.  I will have a PR shortly that does that and then I will make another PR that uses a workflow action to release the chart when the chart's version changes that will create a release and also update the index.yaml

**Comment by krmichel** [comment]
This PR is superseded by PR #623 which has an index.yaml that contains all the available chart versions.

**Comment by krmichel** [comment]
PR #624 should keep the index.yaml up to date going forward

**Comment by wongma7** [comment]
/close

thanks @krmichel

**Pull request closed without merging**
