### PR TITLE
Release 0.9.1

### PR DESCRIPTION
**Pull request by AndyXiangLi**
Releasing version V0.9.1

### CODE REVIEW

**Comment by wongma7** [comment]
Can we cherry pick just the changes we care about ? Or make a 0.10.0 release?

**Comment by AndyXiangLi** [comment]
> Can we cherry pick just the changes we care about ? Or make a 0.10.0 release?

Sure, will cherry pick the necessary fix in this PR and will create a separate one for 0.10.0 release

**Comment by wongma7** [comment]
Thanks. in that case the release note can be trimmed (but we can reuse it for 0.10.0 release)

**Comment by wongma7** [comment]
/lgtm
/approve

ty

**Pull request merged**
