### PR TITLE
[cherry-pick release-1.23] Add compatibility workaround for A1 instance family

### PR DESCRIPTION
**Pull request by ConnorJC3**
/assign @AndrewSirenko

### CODE REVIEW

**Comment by calvinbui** [comment]
will there be any workarounds for v1.25 or v1.26? the helm chart with `a1CompatibilityDaemonSet=true` tries to pull the `v1.26.0-a1compat` tag which doesn't exist.

**Comment by AndrewSirenko** [comment]
Hi @calvinbui, thank you for reaching out about a1compat for v1.25 and 1.26. 

I will work with EKS to try to find out why `public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.25.0-a1compat` and `public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.26.0-a1compat` don't exist. I will have update you later today (by 8pm EST).

If you urgently need to unblock yourself, you can try [replacing the default ecr-public image repository](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/0c459169dd183c1b1fb27443d562cc0f6579a62b/charts/aws-ebs-csi-driver/values.yaml#L6) with `registry.k8s.io/provider-aws/aws-ebs-csi-driver`

The `registry.k8s.io/provider-aws/aws-ebs-csi-driver:v1.26.0-a1compat` image exists. 
```
❯ crane manifest registry.k8s.io/provider-aws/aws-ebs-csi-driver:v1.26.0-a1compat
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "digest": "sha256:f685b489fffdf1c10d0c82d535d138abf6ab84edaaa3a13cd48d930990682352",
    "size": 1637
  },
  "layers": [
    ...
  ]
}
```

**Comment by AndrewSirenko** [comment]
Hi @calvinbui, the a1 compat images are available on ecr-public now [Amazon ECR Public Gallery - EBS CSI driver/aws-ebs-csi-driver](https://gallery.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver)

```
❯ crane digest public.ecr.aws/ebs-csi-driver/aws-ebs-csi-driver:v1.26.0-a1compat
sha256:aff5fff2f34664b2e450794cc050a9834a61ff25fe90b5846252efcf7b817b53
```

**Pull request merged**
