### PR TITLE
Upgrade golangci-lint; Fix linter errors

### PR DESCRIPTION
**Pull request by torredil**
**What is this PR about? / Why do we need it?**
- Upgrade `golangci-lint`: `v1.21.0` ->  `v1.50.1`
- Fix linter errors.

**What testing is done?** 
- `make verify`
- `make test`
- `CI`

Signed-off-by: Eddie Torres <torredil@amazon.com>

### CODE REVIEW

**Review by ConnorJC3 — COMMENTED** [review]
/lgtm

**Review by olemarkus — APPROVED** [review]

**Pull request merged**
