### PR TITLE
Prepare for release v1.6.0

### PR DESCRIPTION
**Pull request by torredil**
Signed-off-by: Eddie Torres <torredil@amazon.com>

### CODE REVIEW

**Comment by torredil** [comment]
@gtxu

**Comment by stevehipwell** [comment]
@torredil is the chart release for v1.6.0 covered in this general workflow or would a PR help get it out sooner?

**Comment by gtxu** [comment]
Hi @stevehipwell , helm chart will have a new version in the following PRs soon. Current PR doesn't cover it yet.

**Pull request merged**
