### PR TITLE
feat: Update index.yaml helm chart version to 0.6.1

### PR DESCRIPTION
**Pull request by galindro**
Signed-off-by: Bruno Galindro da Costa <bruno.galindro@navinfo.eu>

**Is this a bug fix or adding new feature?**
bug fix

**What is this PR about? / Why do we need it?**
It updates the helm chart repository's index.yaml to the latest chart version (0.6.1)

**What testing is done?** 
None

### CODE REVIEW

**Comment by ayberk** [comment]
Hi @galindro, could you please sign the CLA? If you prefer not to do so, I can close this PR and send one myself.

**Comment by galindro** [comment]
@ayberk I did everything related to the CLA as stated on the procedure but I don't know why the PR wasn't be signed... Should I execute some command to tell to @k8s-ci-robot to re-check it?

**Comment by ayberk** [comment]
Just commenting should be enough to trigger a check. Most likely it's a username/email mishap. Could you refer to the previous comment by the bot? Sorry for the inconvenience, but luckily it's a one-time thing.

**Comment by galindro** [comment]
@ayberk , my commit was correctly signed with my github email address:

Signed-off-by: Bruno Galindro da Costa <bruno.galindro@gmail.com>

Should it contain the github username also? The instructions didn't mention that...

**Comment by nckturner** [comment]
@galindro the full commit is this: 

```
commit 01e22d3b294f558768db4d1a229aba1bea199d99 (HEAD -> bump-index-yaml, galindro/bump-index-yaml)
Author: Bruno Galindro da Costa <bruno.galindro@navinfo.eu>
Date:   Fri Oct 16 16:40:15 2020 +0200

    feat: Update index.yaml Helm Chart version to 0.6.1
    
    Signed-off-by: Bruno Galindro da Costa <bruno.galindro@gmail.com>

```

The author is `@navinfo.eu`, which you can change with `git commit --amend --author="Bruno Galindro da Costa <bruno.galindro@gmail.com>"`

**Comment by galindro** [comment]
@nckturner just fixed. Tks for the tip. I really didn't paid attention on the Author name. I was too much focused on the Signed-by...

**Comment by galindro** [comment]
@ayberk / @wongma7 / @nckturner , The tests of my PR failed perhaps because something was missing on the branch gh-pages. Should I open a new PR to merge my changes on master or should I keep them on gh-pages?

**Comment by ayberk** [comment]
@galindro gh-pages is the correct branch, but we don't have any code on that branch so tests were failing. We disabled the tests. If you could send a new PR with your initial commit updating the `index.yaml`, it should work now.

**Comment by ayberk** [comment]
@galindro This should be fixed now. Appreciate the help here! See #620.

**Comment by galindro** [comment]
There is a missing label on the mentioned ticket @ayberk . Someone needs to add it before merge.

**Pull request closed without merging**
