### PR TITLE
Skip sc1 and st1 tests, only test xfs

### PR DESCRIPTION
**Pull request by wongma7**
**Is this a bug fix or adding new feature?** mitigation

**What is this PR about? / Why do we need it?** certain tests are super flaky https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/545. I haven't had much chance to debug so I'm just going to remove redundant tests for now and figure it out later.

**What testing is done?**

### CODE REVIEW

**Review by ayberk — APPROVED** [review]

**Comment by leakingtapan** [comment]
Please create a new issue to track the root cause

**Comment by wongma7** [comment]
@leakingtapan there is #545 i'll keep it open

**Comment by jsafrane** [comment]
Would it make sense to bump io1 IOPS instead of skipping it? IMO it's quite useful to test StorageClass parsing in e2e.

**Comment by jsafrane** [comment]
Nevermind, I can see io1 is still tested.

**Pull request merged**
