### PR TITLE
[helm-chart] csi-snapshotter in ebs-csi-controller now checks for enableVolumeSnapshot before including it in containers

### PR DESCRIPTION
**Pull request by missingcharacter**
**Is this a bug fix or adding new feature?**
bug fix

**What is this PR about? / Why do we need it?**
Fixes https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/942

**What testing is done?** 
locally, yes

### CODE REVIEW

**Comment by wongma7** [comment]
This doesn't fully fix the issue because we might have users who already have the controller and CRDs installed, so they set enableVolumeSnapshot false. In that case they DO want the sidecar still running. 

TBH I'm leaning heavily toward not installing the snapshot controller and CRDS at all : ( https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/635#issuecomment-872534979, let me know your thoughts.

**Comment by missingcharacter** [comment]
@wongma7 

>  I intend to remove the CRDs and controller and simply list it as a prerequisite to the chart

This makes total sense, I think it is best

**Comment by wongma7** [comment]
Yeah my full reasoning is in the comment, @krmichel if we want to stop installing the CRDs and snapshot controller, and instead point users to docs to how to install it (leveraging the help text that prints right after an install) do we need to bump the helm chart major version?

**Comment by missingcharacter** [comment]
@wongma7 
> do we need to bump the helm chart major version?
Yes, please 🙇🏽‍♂️

**Comment by wongma7** [comment]
OK. I'm actually prepping helm chart 1.2.4 with your previous PR right now. So that will leave the 1.x.x series of charts in an okay-ish state (if you set enableVolumeSnapshot true it will install everything you need, if it's false then you might run into #942)

So, after 1.2.4 is released we can take some time to make any other breaking changes we want.

(EFS repo made a 2.0.0 release recently as well , so I am not worried at all about making a new major version too fast or whatever.)

**Comment by missingcharacter** [comment]
@wongma7 is it OK if I just close this PR?

**Comment by missingcharacter** [comment]
Actually, I think I can add a `capabilities` check to install the sidecar if `enableVolumeSnapshot` is true or the snapshot CRDs are present, it is not perfect but it would leave `1.2.4` in a better state

**Comment by krmichel** [comment]
> Yes, please 🙇🏽‍♂️ (I know you are not asking me)

I fully agree.  I already have the second half of the major chart update that needs to do things like getting rid of the old not well-organized values and bump the helm version requirement so I will try to get those done and in PR so we can roll them into 2.0 as well.

**Comment by missingcharacter** [comment]
Ok, this PR should leave `1.2.4` in better shape to then remove CRDs and snapshot controller off it

**Comment by wongma7** [comment]
/lgtm

I'll rebase on this / include it in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/959

**Pull request merged**
