### PR TITLE
Release 0.8.2

### PR DESCRIPTION
**Pull request by AndyXiangLi**
Patch 0.8 version with leaked volume fix

### CODE REVIEW

**Comment by wongma7** [comment]
```
 Failed to compile e2e:
../../../../pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:9:2: missing go.sum entry for module providing package github.com/golang/protobuf/proto (imported by github.com/container-storage-interface/spec/lib/go/csi); to add:
	go get github.com/container-storage-interface/spec/lib/go/csi@v1.2.0
../../../../pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:10:2: missing go.sum entry for module providing package github.com/golang/protobuf/protoc-gen-go/descriptor (imported by github.com/container-storage-interface/spec/lib/go/csi); to add:
	go get github.com/container-storage-interface/spec/lib/go/csi@v1.2.0
../../../../pkg/mod/google.golang.org/grpc@v1.26.0/internal/binarylog/method_logger.go:28:2: missing go.sum entry for module providing package github.com/golang/protobuf/ptypes (imported by github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver); to add:
	go get github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver
../../../../pkg/mod/google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1/googleapis/rpc/status/status.pb.go:11:2: missing go.sum entry for module providing package github.com/golang/protobuf/ptypes/any (imported by google.golang.org/genproto/googleapis/rpc/status); to add:
	go get google.golang.org/genproto/googleapis/rpc/status@v0.0.0-20191220175831-5c49e3ecc1c1
../../../../pkg/mod/google.golang.org/grpc@v1.26.0/binarylog/grpc_binarylog_v1/binarylog.pb.go:9:8: missing go.sum entry for module providing package github.com/golang/protobuf/ptypes/duration (imported by google.golang.org/grpc/binarylog/grpc_binarylog_v1); to add:
	go get google.golang.org/grpc/binarylog/grpc_binarylog_v1@v1.26.0
../../../../pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:11:2: missing go.sum entry for module providing package github.com/golang/protobuf/ptypes/timestamp (imported by github.com/container-storage-interface/spec/lib/go/csi); to add:
	go get github.com/container-storage-interface/spec/lib/go/csi@v1.2.0
../../../../pkg/mod/github.com/container-storage-interface/spec@v1.2.0/lib/go/csi/csi.pb.go:12:2: missing go.sum entry for module providing package github.com/golang/protobuf/ptypes/wrappers (imported by github.com/container-storage-interface/spec/lib/go/csi); to add:
	go get github.com/container-storage-interface/spec/lib/go/csi@v1.2.0
../../../../pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/diff/diff.go:27:2: missing go.sum entry for module providing package github.com/google/go-cmp/cmp (imported by k8s.io/apimachinery/pkg/util/diff); to add:
	go get k8s.io/apimachinery/pkg/util/diff@v0.17.3
tests/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go:26:2: missing go.sum entry for module providing package github.com/onsi/gomega (imported by github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/testsuites); to add:
	go get github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/testsuites
../../../../pkg/mod/k8s.io/kubernetes@v1.17.3/test/e2e/framework/util.go:46:2: missing go.sum entry for module providing package github.com/onsi/gomega/types (imported by k8s.io/kubernetes/test/e2e/framework); to add:
	go get k8s.io/kubernetes/test/e2e/framework@v1.17.3
../../../../pkg/mod/sigs.k8s.io/yaml@v1.1.0/yaml.go:11:2: missing go.sum entry for module providing package gopkg.in/yaml.v2 (imported by k8s.io/kubernetes/test/utils/image); to add:
	go get k8s.io/kubernetes/test/utils/image@v1.17.3 
```
?
/retest

**Comment by ayberk** [comment]
@wongma7 has to approve because we're not in the OWNERS in that branch.

**Pull request merged**
