### PR TITLE
Make hostNetwork configurable for daemonset

### PR DESCRIPTION
**Pull request by bseenu**
**Is this a bug fix or adding new feature?**

bug fix

**What is this PR about? / Why do we need it?**

we want to run the daemonsets in host network, and want to make that configurable

**What testing is done?**

### CODE REVIEW

**Comment by diranged** [comment]
Yes please - can we help get this pushed across the line?

**Comment by ConnorJC3** [comment]
Hi @bseenu - a few things:

First, is there a particular reason you want to run the driver in host network mode? This is a potentially footgun-ish feature, so I'm hesitant to expose it to users without a good reason.

Second, please remove the modifications to `CHANGELOG.md` and `Chart.yaml`. We generally do not accept PRs that add a feature and perform a release at the same time - releases are performed by our maintainers on a semi-regular schedule and take into account details such as backwards compatibility and support policies.

Third, you seem to have some minor test failures, please fix those.

**Comment by diranged** [comment]
> First, is there a particular reason you want to run the driver in host network mode? This is a potentially footgun-ish feature, so I'm hesitant to expose it to users without a good reason.

@ConnorJC3,
  I would put this the other way around ... Is there a particular reason why we _shouldn't be able to use `hostNetwork: true`_ here? This is following the pattern of the `aws-efs-csi-driver` https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/helm-chart-aws-efs-csi-driver-2.4.1/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L56.  Sadly the `aws-efs-csi-driver` chart was updated without much explanation to remove this setting (https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/910#issuecomment-1684324050) ... I have commented and am asking for clarity going forward.

  Fundamentally DaemonSets not using `hostNetwork` have a few problems... not the least of which is the waste of IP space on large clusters (1000+ nodes). There are other issues like the fact that these pods can come up and fail if the CNI isn't ready yet (hint: IP/CIDR exhaustion), and that just causes more pods to be stuck in `ContainerCreating` for no good reason.

**Comment by jacobwolfaws** [comment]
> > First, is there a particular reason you want to run the driver in host network mode? This is a potentially footgun-ish feature, so I'm hesitant to expose it to users without a good reason.
> 
> @ConnorJC3, I would put this the other way around ... Is there a particular reason why we _shouldn't be able to use `hostNetwork: true`_ here? This is following the pattern of the `aws-efs-csi-driver` https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/helm-chart-aws-efs-csi-driver-2.4.1/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L56. Sadly the `aws-efs-csi-driver` chart was updated without much explanation to remove this setting ([kubernetes-sigs/aws-efs-csi-driver#910 (comment)](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/910#issuecomment-1684324050)) ... I have commented and am asking for clarity going forward.
> 
> Fundamentally DaemonSets not using `hostNetwork` have a few problems... not the least of which is the waste of IP space on large clusters (1000+ nodes). There are other issues like the fact that these pods can come up and fail if the CNI isn't ready yet (hint: IP/CIDR exhaustion), and that just causes more pods to be stuck in `ContainerCreating` for no good reason.

@diranged The reason why EFS (and FSx) removed `hostNetwork: true` from our repositories is that it exposes security risks to users. This [link](https://www.elastic.co/guide/en/security/current/kubernetes-pod-created-with-hostnetwork.html) provides a good explanation for what those risks are.

In terms of the PR, I think if users want to configure `hostNetwork: true` they should be able to, just with the knowledge that doing so exposes their cluster to potential security risks.

**Comment by bseenu** [comment]
> > > First, is there a particular reason you want to run the driver in host network mode? This is a potentially footgun-ish feature, so I'm hesitant to expose it to users without a good reason.
> > 
> > 
> > @ConnorJC3, I would put this the other way around ... Is there a particular reason why we _shouldn't be able to use `hostNetwork: true`_ here? This is following the pattern of the `aws-efs-csi-driver` https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/helm-chart-aws-efs-csi-driver-2.4.1/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L56. Sadly the `aws-efs-csi-driver` chart was updated without much explanation to remove this setting ([kubernetes-sigs/aws-efs-csi-driver#910 (comment)](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/910#issuecomment-1684324050)) ... I have commented and am asking for clarity going forward.
> > Fundamentally DaemonSets not using `hostNetwork` have a few problems... not the least of which is the waste of IP space on large clusters (1000+ nodes). There are other issues like the fact that these pods can come up and fail if the CNI isn't ready yet (hint: IP/CIDR exhaustion), and that just causes more pods to be stuck in `ContainerCreating` for no good reason.
> 
> @diranged The reason why EFS (and FSx) removed `hostNetwork: true` from our repositories is that it exposes security risks to users. This [link](https://www.elastic.co/guide/en/security/current/kubernetes-pod-created-with-hostnetwork.html) provides a good explanation for what those risks are.
> 
> In terms of the PR, I think if users want to configure `hostNetwork: true` they should be able to, just with the knowledge that doing so exposes their cluster to potential security risks.

By default the chart would still be having it false, but makes that configurable whoever wants to change it

**Comment by bseenu** [comment]
> Hi @bseenu - a few things:
> 
> First, is there a particular reason you want to run the driver in host network mode? This is a potentially footgun-ish feature, so I'm hesitant to expose it to users without a good reason.
> 
> Second, please remove the modifications to `CHANGELOG.md` and `Chart.yaml`. We generally do not accept PRs that add a feature and perform a release at the same time - releases are performed by our maintainers on a semi-regular schedule and take into account details such as backwards compatibility and support policies.
> 
> Third, you seem to have some minor test failures, please fix those (the Windows test is a known flake and is marked as optional, so you can ignore it, but the other test failures are likely legitimate).

removed the changes to changelog and chart.yaml, Thanks

**Comment by jacobwolfaws** [comment]
@bseenu can you squash the commits in this PR? It seems like they should all be in a single commit

**Comment by ConnorJC3** [comment]
We can let prow squash it

/approve

**Pull request merged**
