### PR TITLE
Update image for runtime deployment

### PR DESCRIPTION
**Pull request by leakingtapan**

### CODE REVIEW

**Comment by dkoshkin** [comment]
We should also include the `liveness-probe` in the diagram right?

**Comment by leakingtapan** [comment]
It will be used here: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/wiki/Architecture-Diagrams

**Comment by leakingtapan** [comment]
> We should also include the `liveness-probe` in the diagram right?

Updated

**Pull request merged**
