### PR TITLE
Upgrade CSI spec to 1.1.0

### PR DESCRIPTION
**Pull request by leakingtapan**
/cc @bertinatto 

This unblocks volume resizing.

### CODE REVIEW

**Comment by bertinatto** [comment]
Thanks, @leakingtapan.

Can't merge now because of failing tests, but it's OK if you don't want to fix it because I already imported this in my working branch.

**Comment by leakingtapan** [comment]
Coverage drop is due to CSI Spec upgrade.

**Comment by leakingtapan** [comment]
The failed test was due to:

```
[91m[1mSummarizing 2 Failures:[0m

[91m[1m[Fail] [0m[90m[ebs-csi-e2e] [single-az] Dynamic Provisioning [0m[91m[1m[It] should create a volume on demand with volumeType "sc1" and fsType "ext3" [0m
[37m/home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/testsuites/testsuites.go:313[0m

[91m[1m[Fail] [0m[90m[ebs-csi-e2e] [single-az] Dynamic Provisioning [0m[91m[1m[It] should create a volume on demand with volumeType "sc1" and fsType "ext2" [0m
[37m/home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e/testsuites/testsuites.go:509[0m

[1m[91mRan 35 of 37 Specs in 1562.276 seconds[0m
[1m[91mFAIL![0m -- [32m[1m33 Passed[0m | [91m[1m2 Failed[0m | [33m[1m0 Pending[0m | [36m[1m2 Skipped[0m
```

It's unrelated to this change. We will revisit all the flaky tests once #192 is done.

**Pull request merged**
