### PR TITLE
Refactor integration test script

### PR DESCRIPTION
**Pull request by leakingtapan**
**Is this a bug fix or adding new feature?**
Fixes: #265

### CODE REVIEW

**Comment by bertinatto** [comment]
What's the difference between this and `test-integration` script? 

Could we have a single script for running integration tests?

**Comment by leakingtapan** [comment]
The test-integration script is running on the ec2 instance. It’s called by aws-k8s-tester, which is called by run-integration-test

**Comment by bertinatto** [comment]
Okay, maybe we can rename them to make this more obvious?

/lgtm

**Pull request merged**
