### PR TITLE
Bump CI k8s version to 1.26.1 (and other CI tools upgrades)

### PR DESCRIPTION
**Pull request by ConnorJC3**
Signed-off-by: Connor Catlett <conncatl@amazon.com>

### CODE REVIEW

**Comment by ConnorJC3** [comment]
Undrafting because 1.26.1 is now available for testing.

**Review by torredil — COMMENTED** [review]
Can we also bump up:

- Helm to `v3.11.0`: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/78c845b11ce452bb90318f8d63bb9807c35240ed/Makefile#L116
- Ginkgo to `v2.7.0`: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/78c845b11ce452bb90318f8d63bb9807c35240ed/hack/e2e/run.sh#L114

Other than that, lgtm, thanks 👍

**Review by torredil — APPROVED** [review]
/lgtm

**Pull request merged**
