### PR TITLE
Support optional ec2 endpoint configuration

### PR DESCRIPTION
**Pull request by geek**
This PR improves on an existing feature introduced in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/e4569c373c609115ce2cf756e4e1646095f7a979. With this change, a user can configure the EC2 endpoint using a config map. For example, to change the EC2 endpoint a user can apply the following:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-meta
  namespace: kube-system
data:
  endpoint: "https://specific.aws.endpoint"
```

Tested locally with setting a custom endpoint and seeing cloud actions being sent to endpoint domain.

Please let me know if there is a different preferred method to set this endpoint as well as if you want me to document this approach anywhere.

### CODE REVIEW

**Comment by geek** [comment]
@AndyXiangLi or @gnufied do you need anything else from me before starting the review?

**Comment by AndyXiangLi** [comment]
Looks like cla check fail for some reason, can you make sure the email you have configured for the git is signed on CLA?

**Comment by geek** [comment]
@AndyXiangLi thanks, the email for the CLA does match the git commit. Do you think I should try resubmitting to rerun the cla/linuxfoundation check or is there a way that you can trigger it to rerun?

**Comment by AndyXiangLi** [comment]
Yeah, can you do the commit one more time?

**Comment by geek** [comment]
@AndyXiangLi the CLA check is passing after rerunning it from the new commit.

**Comment by gnufied** [comment]
BTW does the environment variable needs to set for node daemonset too? I have been wondering if custom endpoints affect AWS metadata service and so far I can't find anything conclusive. Node side of driver does seem to query metadata information fwiw.

**Comment by geek** [comment]
@gnufied in my testing I don't think I had to set the environment variable on the node daemonset.

**Comment by geek** [comment]
@gnufied or @AndyXiangLi do you need anything else to approve this PR?

**Comment by torredil** [comment]
Thank you for your contribution :)
/lgtm
/approve
/hold

cc @gtxu @rdpsin

**Review by torredil — APPROVED** [review]

**Pull request merged**
