### PR TITLE
Merge 1.12+ Deploy Manifests

### PR DESCRIPTION
**Pull request by christopherhein**
**Is this a bug fix or adding new feature?**
Improvement

**What is this PR about? / Why do we need it?**
This merges the deployment manifests into a single file so that you don't have to clone the repo to deploy the CSI driver. This also makes the `Secret` optional.

### CODE REVIEW

**Comment by christopherhein** [comment]
```shell
→ ./hack/verify-all.sh 
Verifying gofmt
No issue found
Verifying govet
Done
Congratulations! All Go source files have been linted.
```

**Comment by leakingtapan** [comment]
@christopherhein Thx for the quick patch! Did you get a chance to test the driver with optional secret?

**Comment by christopherhein** [comment]
> @christopherhein Thx for the quick patch! Did you get a chance to test the driver with optional secret?

Working on it now.

**Pull request closed without merging**
