### PR TITLE
Remove `/vendor` directory

### LINKED ISSUE #909: Consider releasing kustomize archives
**Is your feature request related to a problem?/Why is this needed**
`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.10"` takes a long time.

/feature

**Describe the solution you'd like in detail**
Publish zip, tarball archives with just the `deploy/` files.

**Describe alternatives you've considered**
Publish a tag with just the `deploy/` files.

**Additional context**
The main reason for `kubectl apply -k` being slow is it's downloading ~68 MB of files. The `deploy/` dir can be just a 44 KB archive instead.

### LINKED ISSUE #1326: Remove `/vendor` directory
It's no longer 2015 or Go <=1.11, so we should get rid of the `/vendor` directory and just use Go modules.

We recently [did this for iam authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/463) and it removes a bunch of code from the repository that no longer is required.

### PR DESCRIPTION
**Pull request by torredil**
Signed-off-by: torredil <torredil@amazon.com>

**Is this a bug fix or adding new feature?**

- Remove `/vendor` directory
- Cache dependency layer in Dockerfile

closes #1326 
closes #909

### CODE REVIEW

**Review by wmesard — APPROVED** [review]

**Review by jaypipes — APPROVED** [review]
Yes, please! :) :+1:

**Pull request merged**
