### PR TITLE
Bump chart-releaser-action to v1.2.1

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

**What testing is done?**

### CODE REVIEW

**Comment by vdhanan** [comment]
could you please explain why we should upgrade to 1.2.1?

**Comment by gliptak** [comment]
@vdhanan regular care&feeding

**Pull request merged**
