### PR TITLE
1182 quote extra tags arg

### PR DESCRIPTION
**Pull request by Kaezon**
**Is this a bug fix or adding new feature?**
Bug fix for #1182

**What is this PR about? / Why do we need it?**
This fix add quotes around the extra-tags argument in order to prevent special characters such as ":" from breaking the manifest YAML after template rendering.

**What testing is done?**
Manual test with "helm template" to validate render output, as well as a live deployment to make sure a deployment would run with the offending tag value.

### CODE REVIEW

**Comment by Kaezon** [comment]
Trying to get the CLA taken care of ASAP

**Comment by torredil** [comment]
Thank you for your contribution :)
/lgtm
/hold

cc @gtxu @rdpsin

**Review by torredil — APPROVED** [review]

**Pull request merged**
