### PR TITLE
Update helm charts for a secrect exposure

### PR DESCRIPTION
**Pull request by gtxu**
Removed external-snapshot-role gain u-necessary access to secrets

### CODE REVIEW

**Comment by AndyXiangLi** [comment]
/approve
/lgtm
thanks

**Comment by stevehipwell** [comment]
@AndyXiangLi if access to secrets might still be required shouldn't this removal have been a conditional switch rather than requiring manual changes to the yaml?

**Comment by gtxu** [comment]
This will not require customers to modify it. Leaving this comment for reference if the our snapshot future feature that requires secret access. i.e. customers use other credentials to encrypt snapshot volume. Currently, the driver don't use any secret, so do the snapshotter. So we comment this part.

**Comment by stevehipwell** [comment]
Thanks @gtxu I think the comment confused me reading as a user, but reading as a maintainer it makes sense.

**Pull request merged**
